version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3

jobs:
  install-browser:
    steps:
      - run:
          command: npx @puppeteer/browsers install chrome@stable

workflows:
  use-my-orb:
    jobs:
      - install-browser
      - cypress/run:
          requires:
            - install-browser
          cypress-command: npm run cy:ci
          parallelism: 2 # use 2 CircleCI machines to finish quickly
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - main
    jobs:
      - cypress/run:
          cypress-command: npm run cy:ci
          parallelism: 2 # use 2 CircleCI machines to finish quickly
